/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ModulesRouteImport } from './routes/modules'
import { Route as RagRouteImport } from './routes/rag'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SharedShareTokenRouteImport } from './routes/shared.$shareToken'
import { Route as SharedChatShareTokenRouteImport } from './routes/shared.chat.$shareToken'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesRoute = ModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => rootRouteImport,
} as any)
const RagRoute = RagRouteImport.update({
  id: '/rag',
  path: '/rag',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedShareTokenRoute = SharedShareTokenRouteImport.update({
  id: '/shared/$shareToken',
  path: '/shared/$shareToken',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedChatShareTokenRoute = SharedChatShareTokenRouteImport.update({
  id: '/shared/chat/$shareToken',
  path: '/shared/chat/$shareToken',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/modules': typeof ModulesRoute
  '/rag': typeof RagRoute
  '/register': typeof RegisterRoute
  '/shared/$shareToken': typeof SharedShareTokenRoute
  '/shared/chat/$shareToken': typeof SharedChatShareTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/modules': typeof ModulesRoute
  '/rag': typeof RagRoute
  '/register': typeof RegisterRoute
  '/shared/$shareToken': typeof SharedShareTokenRoute
  '/shared/chat/$shareToken': typeof SharedChatShareTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/modules': typeof ModulesRoute
  '/rag': typeof RagRoute
  '/register': typeof RegisterRoute
  '/shared/$shareToken': typeof SharedShareTokenRoute
  '/shared/chat/$shareToken': typeof SharedChatShareTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/modules'
    | '/rag'
    | '/register'
    | '/shared/$shareToken'
    | '/shared/chat/$shareToken'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/modules'
    | '/rag'
    | '/register'
    | '/shared/$shareToken'
    | '/shared/chat/$shareToken'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/modules'
    | '/rag'
    | '/register'
    | '/shared/$shareToken'
    | '/shared/chat/$shareToken'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ModulesRoute: typeof ModulesRoute
  RagRoute: typeof RagRoute
  RegisterRoute: typeof RegisterRoute
  SharedShareTokenRoute: typeof SharedShareTokenRoute
  SharedChatShareTokenRoute: typeof SharedChatShareTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules': {
      id: '/modules'
      path: '/modules'
      fullPath: '/modules'
      preLoaderRoute: typeof ModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rag': {
      id: '/rag'
      path: '/rag'
      fullPath: '/rag'
      preLoaderRoute: typeof RagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared/$shareToken': {
      id: '/shared/$shareToken'
      path: '/shared/$shareToken'
      fullPath: '/shared/$shareToken'
      preLoaderRoute: typeof SharedShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared/chat/$shareToken': {
      id: '/shared/chat/$shareToken'
      path: '/shared/chat/$shareToken'
      fullPath: '/shared/chat/$shareToken'
      preLoaderRoute: typeof SharedChatShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ModulesRoute: ModulesRoute,
  RagRoute: RagRoute,
  RegisterRoute: RegisterRoute,
  SharedShareTokenRoute: SharedShareTokenRoute,
  SharedChatShareTokenRoute: SharedChatShareTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
